### ISSUE TITLE
[Bug]: DeprecationWarning in NodeJS 24.x

### ISSUE THREAD

**Issue by jwhitmarsh** [Vonage/vonage-node-sdk#1020]
### Node Version

24.x

### Platform

Mac (Apple Silcon)

### SDK Version

3.x.x

### Code Sample

Basic auth instantiation:

```
    const vonageAuth = new Auth({
        apiKey: XXX,
        apiSecret: YYY,
    });
```

### Expected Behavior

Not to throw a deprecation warning

### Actual Behavior

Throws a deprecation warning:

```
(node:57) [DEP0187] DeprecationWarning: Passing invalid argument types to fs.existsSync is deprecated
    at existsSync (node:fs:282:15)
    at new Auth (/usr/src/app/node_modules/@vonage/auth/lib/auth.ts:87:19)
```

The package.json supports NodeJS >= 20, and doesn't say anything about not supporting >= 22, but I can see from the node version options in this bug report template that there's some lag with support.

**Comment by manchuck** [comment]
Thanks @jwhitmarsh. I noticed this the other day while working on #1019. I'm going to add a fix, which will go out along with the work in that PR.

**Comment by manchuck** [comment]
This has been resolved

**Comment by dreams-money** [comment]
Is this update included in the latest release? I'm still seeing this warning with Node v24.14.1 and @vonage/server-sdk 3.27.0.

**Comment by manchuck** [comment]
It should be but there is an issue with CJS and ESM builds for earlier version of Node. I'm going to resolve these warnings with that work
